# This is a boilerplate parameters config generated for pipeline 'data_science'
# using Kedro 0.17.5.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.17.5/04_kedro_project_setup/02_configuration.html#parameters
random_state: 42

models:
  random_forest:
    model_class: sklearn.ensemble.RandomForestRegressor
    model_name: random_forest
    default_params: null
    params:
        n_estimators: list(map(int, np.linspace(start = 50, stop = 1500, num = 100)))
        max_depth: np.append(list(map(int, np.linspace(3, 100, num = 50))), [None])
        min_samples_split: [2, 5, 10,  20]
        min_samples_leaf: [1, 2, 4, 8]
  ada:
    model_class: sklearn.ensemble.AdaBoostRegressor
    model_name: ada
    default_params: null
    params:
        n_estimators: list(map(int, np.linspace(start = 50, stop = 1500, num = 100)))
        learning_rate: stats.loguniform(0.05, 0.3)